<?php
$i=0;
$arr = [
    'name' => [
        'id' => ++$i,
        'field' => 'Имя*',
        'required' => 1,
        'type' => 'text',
        'key' => 'name',
        'placeholder' => 'Валентина'
    ], 
    'parent' => [
        'id' => ++$i,
        'field' => 'Отчество',
        'required' => 0,
        'type' => 'text',
        'key' => 'parent',
        'placeholder' => 'Петровна'
    ], 
    'parent-not' => [
        'id' => ++$i,
        'field' => 'Нет отчества',
        'required' => 0,
        'type' => 'checkbox',
        'key' => 'parent-not',
    ], 
    'surname' => [
        'id' => ++$i,
        'field' => 'Фамилия*',
        'required' => 1,
        'type' => 'text',
        'key' => 'surname',
        'placeholder' => 'Васильева'
    ], 
    'birthday' => [
        'id' => ++$i,
        'field' => 'Дата рождения*',
        'required' => 1, 
        'type' => 'date',
        'key' => 'birthday',
        'min' => "1900-01-01",
        'max' => date("Y-m-d"),
    ], 
    'email' => [
        'id' => ++$i,
        'field' => 'Почта*',
        'required' => 1,
        'type' => 'text',
        'key' => 'email',
        'placeholder' => 'valentina@gmail.com',
    ], 
    'phone' => [
        'id' => ++$i,
        'field' => 'Мобильный телефон*',
        'required' => 1,
        'type' => 'tel',
        'key' => 'phone',
        'placeholder' => '89061234567',
    ], 
    'city' => [
        'id' => ++$i,
        'field' => 'Город*',
        'required' => 1,
        'type' => 'text',
        'key' => 'city',
        'placeholder' => 'г.Санкт-Петербург',
    ], 
    'street' => [
        'id' => ++$i,
        'field' => 'Улица*',
        'required' => 1,
        'type' => 'text',
        'key' => 'street',
        'placeholder' => 'Некрасова',
    ], 
    'house' => [
        'id' => ++$i,
        'field' => 'Дом/квартира*',
        'required' => 1,
        'type' => 'text',
        'key' => 'house',
        'placeholder' => '56/11',
    ], 
    'same-adress' => [
        'id' => ++$i,
        'field' => 'По прописке',
        'required' => 1,
        'type' => 'checkbox',
        'key' => 'same-adress',
    ], 
    'city1' => [
        'id' => ++$i,
        'field' => 'Город*',
        'required' => 1,
        'type' => 'text',
        'key' => 'city1',
        'placeholder' => 'г.Москва',
    ], 
    'street1' => [
        'id' => ++$i,
        'field' => 'Улица*',
        'required' => 1,
        'type' => 'text',
        'key' => 'street1',
        'placeholder' => 'Ломоносова',
    ], 
    'house1' => [
        'id' => ++$i,
        'field' => 'Дом/квартира*',
        'required' => 1,
        'type' => 'text',
        'key' => 'house1',
        'placeholder' => '13/6',
    ], 
    'position' => [
        'id' => ++$i,
        'field' => 'Желаемая должность*',
        'required' => 1, 
        'type' => 'text',
        'key' => 'position',
        'placeholder' => 'директор отдела рекламы',
    ], 
    'salary' => [
        'id' => ++$i,
        'field' => 'Минимальный порог желаемой заработной платы (руб/мес)*',
        'required' => 1,               
        'type' => 'number',
        'key' => 'salary',
        'placeholder' => '50 000',
    ], 
    'education-year' => [
        'id' => ++$i,
        'field' => 'Год выпуска*',
        'required' => 1,               
        'type' => 'number',
        'key' => 'education-year',
        'placeholder' => '2007',
        'min' => (date("Y")-100),
        'max' => date("Y"),
    ], 
    'education' => [
        'id' => ++$i,
        'field' => 'Название образовательного учреждения*',
        'required' => 1,               
        'type' => 'text',
        'key' => 'education',
        'placeholder' => 'Московский Государственный Технический Университет',
    ], 
    'specializing' => [
        'id' => ++$i,
        'field' => 'Названия факультета или специализация*',
        'required' => 1,              
        'type' => 'text',
        'key' => 'specializing',
        'placeholder' => 'маркетинг',
    ], 
    'year-experience' => [
        'id' => ++$i,
        'field' => 'Опыт работы (количество лет)*',
        'required' => 1,               
        'type' => 'number',
        'key' => 'year-experience',
        'placeholder' => '3',
        'min' => 0,
        'max' => 50,
    ], //первая работа
    'income-last-job' => [
        'id' => ++$i,
        'field' => 'Начало работы*',
        'required' => 1,               
        'type' => 'month',
        'key' => 'income-last-job',
        'min' => '1950-01',
        'max' => date("Y-m"),
    ], 
    'drop-last-job' => [
        'id' => ++$i,
        'field' => 'Дата увольнения*',
        'required' => 1,               
        'type' => 'month',
        'key' => 'drop-last-job',
        'min' => '1950-01',
        'max' => date("Y-m"),
    ], 
    'last-post' => [
        'id' => ++$i,
        'field' => 'Должность*',
        'required' => 1,              
        'type' => 'text',
        'placeholder' => 'коммерческий директор',
        'key' => 'last-post',
    ], 
    'organisation' => [
        'id' => ++$i,
        'field' => 'Наименование организации*',
        'required' => 1,               
        'type' => 'text',
        'placeholder' => 'ООО Атомстройкомлекс',
        'key' => 'organisation',
    ], 
    'about-job' => [
        'id' => ++$i,
        'field' => 'Основные должностные обязанности',
        'required' => 0,               
        'type' => 'textarea',
        'placeholder' => 'Планирование рабочих процессов на текущую неделю, контроль сотрудников по факту выполненных работ',
        'key' => 'about-job',
    ], 
      // второе место работы
    'income-last-job-2' => [
        'id' => ++$i,
        'field' => 'Начало работы',
        'required' => 0,              
        'type' => 'month',
        'key' => 'income-last-job-2',
        'min' => '1950-01',
        'max' => date("Y-m"),
    ],
    'drop-last-job-2' => [
        'id' => ++$i,
        'field' => 'Дата увольнения',
        'required' => 0,              
        'type' => 'month',
        'key' => 'drop-last-job-2',
        'min' => '1950-01',
        'max' => date("Y-m"),
    ], 
    'last-post-2' => [
        'id' => ++$i,
        'field' => 'Должность',
        'required' => 0,               
        'type' => 'text',
        'placeholder' => 'коммерческий директор',
        'key' => 'last-post-2',
    ], 
    'organisation-2' => [
        'id' => ++$i,
        'field' => 'Наименование организации',
        'required' => 0,               
        'type' => 'text',
        'placeholder' => 'ООО Атомстройкомлекс',
        'key' => 'organisation-2',
    ],
    'about-job-2' => [
        'id' => ++$i,
        'field' => 'Основные должностные обязанности',
        'required' => 0,              
        'type' => 'textarea',
        'placeholder' => 'Планирование рабочих процессов на текущую неделю, контроль сотрудников по факту выполненных работ',
        'key' => 'about-job-2',
    ], 
    'send-mail' => [
        'id' => ++$i,
        'field' => 'Отправить копию на указанную почту',
        'required' => 0,
        'type' => 'checkbox',
        'key' => 'send-mail',
    ], 
    'open' => [
        'id' => ++$i,
        'field' => 'Создать и открыть',
        'required' => 0,
        'type' => 'submit',
        'key' => 'open',
    ], 
    'download' => [
        'id' => ++$i,
        'field' => 'Скачать',
        'required' => 0,
        'type' => 'submit',
        'key' => 'download',
    ],
];